### ISSUE TITLE
Could you give a use case of waymo dataset in Det3D?

### ISSUE THREAD

**Issue by DapengFeng** [cmpute/d3d#1]

**Comment by DapengFeng** [comment]
[Det3D](https://github.com/poodarchu/Det3D)

**Comment by cmpute** [comment]
Sorry I currently use this library in my own project , which is like Det3D but not the same. I haven't tried to integrate this into other frameworks like Det3D or openMM3D. However, the interface for the datasets is quite straight-forward and I think there won't be too much trouble using it in other frameworks.

**Comment by DapengFeng** [comment]
Thanks for your comment and the excellent work. I will try it by myself.

**Comment by DapengFeng** [comment]
Could you explain the coordinate system used in this project?

**Comment by cmpute** [comment]
For object attached coordinate, I use FLU style coordinate system (front-x, left-y, up-z)
