### ISSUE TITLE
How to use modified Bessel autograd function in Pytorch?

### ISSUE THREAD

**Issue by CatOneTwo** [cmpute/d3d#5]
Hi, thanks for your work! I have noticed that you provide "the modified Bessel autograd function in Pytorch with GPU support" in this project, but how to use it to realize von-Mises NLL Loss for angular uncertainty estimation, thank you!

**Comment by cmpute** [comment]
Hi, I haven't maintained the project for a while, and not for a foreseeable future. The code related to that is located at https://github.com/cmpute/d3d/blob/master/d3d/math/__init__.py. You can implement it by copying the related code to your project.
