### ISSUE TITLE
d3d installation error

### ISSUE THREAD

**Issue by CatOneTwo** [cmpute/d3d#6]
Hi, when I tried to install d3d with `pip install d3d`, an error occurred, and the log is below.

`Building wheels for collected packages: d3d
  Building wheel for d3d (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [117 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build
        Command:
          /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/cmake/data/bin/cmake /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPYTHON_LIBRARY:PATH=/home/hys/miniconda3/envs/where2comm/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython3_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython3_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DCMAKE_PREFIX_PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- The CUDA compiler identification is NVIDIA 11.3.58
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda-11.3/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda-11.3 (found version "11.3")
      -- Caffe2: CUDA detected: 11.3
      -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.3/bin/nvcc
      -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.3
      -- Caffe2: Header version is: 11.3
      -- Found CUDNN: /usr/local/cuda-11.3/lib64/libcudnn.so
      -- Found cuDNN: v8.2.1  (include: /usr/local/cuda-11.3/include, library: /usr/local/cuda-11.3/lib64/libcudnn.so)
      -- /usr/local/cuda-11.3/lib64/libnvrtc.so shorthash is 8aa72235
      -- Autodetected CUDA architecture(s):  8.6 8.6 8.6 8.6 8.6 8.6 8.6 8.6
      -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
      CMake Warning at /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
        static library kineto_LIBRARY-NOTFOUND not found.
      Call Stack (most recent call first):
        /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
        CMakeLists.txt:8 (find_package)

      -- Found Torch: /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch/lib/libtorch.so
      -- Found PythonInterp: /home/hys/miniconda3/envs/where2comm/bin/python (found version "3.7.15")
      -- Found PythonLibs: /home/hys/miniconda3/envs/where2comm/lib/libpython3.7m.so (found version "3.7.15")
      CMake Error at CMakeLists.txt:25 (set_target_properties):
        set_target_properties called with incorrect number of arguments.

      -- Found Cython: /home/hys/miniconda3/envs/where2comm/bin/cython
      -- Found NumPy: /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include (found version "1.21.5")
      -- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 646, in setup
          languages=cmake_languages,
        File "/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/cmaker.py", line 338, in configure
          "An error occurred while configuring with CMake.\n"

      An error occurred while configuring with CMake.
        Command:
          /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/cmake/data/bin/cmake /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPYTHON_LIBRARY:PATH=/home/hys/miniconda3/envs/where2comm/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython3_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython3_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DCMAKE_PREFIX_PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4
        Working directory:
          /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for d3d
  Running setup.py clean for d3d
Failed to build d3d
Installing collected packages: d3d
  Running setup.py install for d3d ... error
  error: subprocess-exited-with-error

  × Running setup.py install for d3d did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,

      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build
        Command:
          /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/cmake/data/bin/cmake /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPYTHON_LIBRARY:PATH=/home/hys/miniconda3/envs/where2comm/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython3_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython3_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DCMAKE_PREFIX_PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch -DCMAKE_BUILD_TYPE:STRING=Release

      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- The CUDA compiler identification is NVIDIA 11.3.58
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda-11.3/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda-11.3 (found version "11.3")
      -- Caffe2: CUDA detected: 11.3
      -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.3/bin/nvcc
      -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.3
      -- Caffe2: Header version is: 11.3
      -- Found CUDNN: /usr/local/cuda-11.3/lib64/libcudnn.so
      -- Found cuDNN: v8.2.1  (include: /usr/local/cuda-11.3/include, library: /usr/local/cuda-11.3/lib64/libcudnn.so)
      -- /usr/local/cuda-11.3/lib64/libnvrtc.so shorthash is 8aa72235
      -- Autodetected CUDA architecture(s):  8.6 8.6 8.6 8.6 8.6 8.6 8.6 8.6
      -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
      CMake Warning at /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
        static library kineto_LIBRARY-NOTFOUND not found.
      Call Stack (most recent call first):
        /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
        CMakeLists.txt:8 (find_package)

      -- Found Torch: /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch/lib/libtorch.so
      -- Found PythonInterp: /home/hys/miniconda3/envs/where2comm/bin/python (found version "3.7.15")
      -- Found PythonLibs: /home/hys/miniconda3/envs/where2comm/lib/libpython3.7m.so (found version "3.7.15")
      CMake Error at CMakeLists.txt:25 (set_target_properties):
        set_target_properties called with incorrect number of arguments.

      -- Found Cython: /home/hys/miniconda3/envs/where2comm/bin/cython
      -- Found NumPy: /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include (found version "1.21.5")
      -- Performing Test Weak Link MODULE -> SHARED (gnu_ld_ignore) - Success
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      _modinit_prefix:PyInit_
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 646, in setup
          languages=cmake_languages,
        File "/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/cmaker.py", line 338, in configure
          "An error occurred while configuring with CMake.\n"

      An error occurred while configuring with CMake.
        Command:
          /home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/cmake/data/bin/cmake /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-install -DPYTHON_VERSION_STRING:STRING=3.7.15 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPYTHON_LIBRARY:PATH=/home/hys/miniconda3/envs/where2comm/lib/libpython3.7m.so -DPython_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/hys/miniconda3/envs/where2comm/bin/python -DPython3_ROOT_DIR:PATH=/home/hys/miniconda3/envs/where2comm -DPython3_INCLUDE_DIR:PATH=/home/hys/miniconda3/envs/where2comm/include/python3.7m -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/numpy/core/include -DCMAKE_PREFIX_PATH=/home/hys/miniconda3/envs/where2comm/lib/python3.7/site-packages/torch -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4
        Working directory:
          /tmp/pip-install-h23dylw2/d3d_d985b53dc8c841468daab3817989f1e4/_skbuild/linux-x86_64-3.7/cmake-build
      Please see CMake's output for more information.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> d3d

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

The cmake version is 3.24.3
could you tell me how to fix it, thank you~

**Comment by cmpute** [comment]
Hmm I guess it's due to incompatible CMake version. Could you try CMake 3.18?

**Comment by GiacomoDamicantonio** [comment]
I'm having the same problem, I've tried with every version available and it does not work

**Comment by cmpute** [comment]
Please use alternative repos in future, as I'm not going to maintain this repo. Thanks.
