### ISSUE TITLE
Error compiling Cython file:

### ISSUE THREAD

**Issue by nican2018** [cmpute/d3d#7]
Hello

Please, I'm installing d3d. I'm getting this error after running python setup.py install, I have been trying to search online I didn't get any clear way to solve this. 
I need help thanks.
Error compiling Cython file:
------------------------------------------------------------
...
                pred_key = pred_labels[i] << 16 | pred_ids[i]

            # increase counter
            gt_iter = counter.find(gt_key)
            if gt_iter == counter.end():
                gt_iter = counter.insert(gt_iter, pair[uint32_t, unordered_map[uint32_t, int]](gt_key, unordered_map[uint32_t, int]()))
                                         ^
------------------------------------------------------------

/home/s_214708038/d3d/d3d/benchmarks.pyx:1015:41: Cannot assign type 'iterator' to 'const_iterator'

Error compiling Cython file:
------------------------------------------------------------
...
                gt_counter[gt_key] = 0
            gt_counter[gt_key] += 1

            pred_iter = deref(gt_iter).second.find(pred_key)
            if pred_iter == deref(gt_iter).second.end():
                pred_iter = deref(gt_iter).second.insert(pred_iter, pair[uint32_t, int](pred_key, 0))
                                                         ^
------------------------------------------------------------

/home/s_214708038/d3d/d3d/benchmarks.pyx:1021:57: Cannot assign type 'iterator' to 'const_iterator'
d3d/CMakeFiles/benchmarks.dir/build.make:73: recipe for target 'd3d/benchmarks.cxx' failed
make[2]: *** [d3d/benchmarks.cxx] Error 1
CMakeFiles/Makefile2:214: recipe for target 'd3d/CMakeFiles/benchmarks.dir/all' failed
make[1]: *** [d3d/CMakeFiles/benchmarks.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/opt/conda/envs/coalign/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/opt/conda/envs/coalign/lib/python3.7/site-packages/skbuild/cmaker.py", line 696, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/opt/conda/envs/coalign/lib/python3.7/site-packages/skbuild/cmaker.py", line 741, in make_impl
    raise SKBuildError(msg)

An error occurred while building with CMake.
  Command:
    /opt/conda/envs/coalign/lib/python3.7/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /home/s_214708038/d3d
  Working directory:
    /home/s_214708038/d3d/_skbuild/linux-x86_64-3.7/cmake-build
Please check the install target is valid and see CMake's output for more information.

**Comment by cmpute** [comment]
This issue is related to your Cython version. I won't maintain this repo in future so please consider alternatives.
